### 07. Анализ пропусков как скрытого фактора

Студенты, не указавшие уровень образования родителей, отличаются от остальных? Может ли сам факт пропуска (нежелание / невозможность ответить) коррелировать с их успеваемостью, ментальным здоровьем или социальным статусом?

In [1]:
import sys
import os
from pathlib import Path

project_root = Path(os.getcwd()).parent 
sys.path.insert(0, str(project_root))

from src.preparation import load_df
df = load_df()

In [17]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import src.constants as cnst 

plt.rcParams['font.family'] = 'Arial'

df_02_07 = df.copy()

df_02_07['is_parent_edu_hidden'] = df_02_07.parental_education_level.isna()

res_02_07 = df_02_07.groupby('is_parent_edu_hidden').agg(
    avg_exam_score=('exam_score', 'mean'), 
    avg_study_hours=('study_hours_per_day', 'mean'), 
    pct_part_time_job=('part_time_job', lambda i: (i == 'Yes').sum() / i.count() * 100), 
    avg_attendance_pct=('attendance_percentage', 'mean'), 
    pct_poor_internet_quality=('internet_quality', lambda i: (i == 'Poor').sum() / i.count() * 100), 
    avg_mental_health=('mental_health_rating', 'mean')
).round(1)

display(res_02_07)

df_02_07_flt = df_02_07.loc[df_02_07.is_parent_edu_hidden == True]
pd.crosstab(
    index=df_02_07_flt.age, columns=df_02_07_flt.gender
)

,avg_exam_score,avg_study_hours,pct_part_time_job,avg_attendance_pct,pct_poor_internet_quality,avg_mental_health
is_parent_edu_hidden,,,,,,
False,69.6,3.5,21.6,83.9,16.2,5.5
True,70.0,3.7,20.9,86.6,16.5,5.2

gender  Female  Male  Other
age
17           5     5      2
18           6     2      0
19           8     3      1
20           4     5      0
21           4     6      1
22           5     6      0
23           9     6      0
24           7     4      2

#### 07. Выводы 

Анализ пропусков показал, что они [пропуски] распределены равномерно. Студенты, скрывшие уровень образования родителей, не имеют значимых отличий по успеваемости, ментальному здоровью, посещаемости, полу, возрасту. Кросстабуляция не выявила специфических «скрытных» демографических групп. Таким образом, пропуски в столбце parental_education_level являются случайными (MCAR — Missing Completely At Random) и не влияют на анализ.