### 0. Первичный осмотр данных

In [ ]:
import pandas as pd 

df = pd.read_csv('../data/raw.csv')
df.info()
display(df.head())
display(df.describe())
display(df.select_dtypes(include='str').describe())

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 16 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   student_id                     1000 non-null   str
 1   age                            1000 non-null   int64
 2   gender                         1000 non-null   str
 3   study_hours_per_day            1000 non-null   float64
 4   social_media_hours             1000 non-null   float64
 5   netflix_hours                  1000 non-null   float64
 6   part_time_job                  1000 non-null   str
 7   attendance_percentage          1000 non-null   float64
 8   sleep_hours                    1000 non-null   float64
 9   diet_quality                   1000 non-null   str
 10  exercise_frequency             1000 non-null   int64
 11  parental_education_level       909 non-null    str
 12  internet_quality               1000 non-null   str
 13  mental_health_rating           1000 non-null   int64
 14  extracurricular_participation  1000 non-null   str
 15  exam_score                     1000 non-null   float64
dtypes: float64(6), int64(3), str(7)
memory usage: 125.1 KB

,student_id,age,gender,study_hours_per_day,social_media_hours,netflix_hours,part_time_job,attendance_percentage,sleep_hours,diet_quality,exercise_frequency,parental_education_level,internet_quality,mental_health_rating,extracurricular_participation,exam_score
0,S1000,23,Female,0.0,1.2,1.1,No,85.0,8.0,Fair,6,Master,Average,8,Yes,56.2
1,S1001,20,Female,6.9,2.8,2.3,No,97.3,4.6,Good,6,High School,Average,8,No,100.0
2,S1002,21,Male,1.4,3.1,1.3,No,94.8,8.0,Poor,1,High School,Poor,1,No,34.3
3,S1003,23,Female,1.0,3.9,1.0,No,71.0,9.2,Poor,4,Master,Good,1,Yes,26.8
4,S1004,19,Female,5.0,4.4,0.5,No,90.9,4.9,Fair,3,Master,Good,1,No,66.4

,age,study_hours_per_day,social_media_hours,netflix_hours,attendance_percentage,sleep_hours,exercise_frequency,mental_health_rating,exam_score
count,1000.0000,1000.00000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,20.4980,3.55010,2.505500,1.819700,84.131700,6.470100,3.042000,5.438000,69.601500
std,2.3081,1.46889,1.172422,1.075118,9.399246,1.226377,2.025423,2.847501,16.888564
min,17.0000,0.00000,0.000000,0.000000,56.000000,3.200000,0.000000,1.000000,18.400000
25%,18.7500,2.60000,1.700000,1.000000,78.000000,5.600000,1.000000,3.000000,58.475000
50%,20.0000,3.50000,2.500000,1.800000,84.400000,6.500000,3.000000,5.000000,70.500000
75%,23.0000,4.50000,3.300000,2.525000,91.025000,7.300000,5.000000,8.000000,81.325000
max,24.0000,8.30000,7.200000,5.400000,100.000000,10.000000,6.000000,10.000000,100.000000

,student_id,gender,part_time_job,diet_quality,parental_education_level,internet_quality,extracurricular_participation
count,1000,1000,1000,1000,909,1000,1000
unique,1000,3,2,3,3,3,2
top,S1000,Female,No,Fair,High School,Good,No
freq,1,481,785,437,392,447,682

### 1. Проверка корректности данных

In [ ]:
df.isna().sum()  # -> только 91 пропуск в колонке `parental_education_level`
df.duplicated().sum()  # 0 -> полных дубликатов нет 
df.student_id.nunique() == len(df)  # True -> ID студентов уникальны

True

### 2. Пояснения к колокнкам
***student_id*** — уникальный идентификатор студента (строка)

***age*** — возраст студента в годах (целое число, 17-24)

***gender*** — пол студента (строковая категория, Male / Female / Other)

***study_hours_per_day*** — сколько часов в день студент тратит на учёбу (дробное число, 0-8.3)

***social_media_hours*** — сколько часов в день уходит на соцсети (дробное число, 0-7.2)

***netflix_hours*** — сколько часов в день студент смотрит Netflix (дробное число, 0-5.4)

***part_time_job*** — наличие подработки (Yes / No)

***attendance_percentage*** — процент посещаемости занятий (дробное число, 56-100%)

***sleep_hours*** — сколько часов в сутки студент спит (дробное число, 3.2-10)

***diet_quality*** — качество питания (строковая категория, Poor / Fair / Good)

***exercise_frequency*** — частота физических упражнений (целое число, 0-6)

***parental_education_level*** — уровень образования родителей (строковая категория, High School / Bachelor / Master), содержит 91 пропуск  

***internet_quality*** — качество интернет-соединения (строковая категория, Good / Average / Poor)

***mental_health_rating*** — оценка психического здоровья (целое число, 1-10)

***extracurricular_participation*** — участие во внеучебной деятельности (Yes / No)

***exam_score*** — итоговый балл за экзамен (дробное число, 18.4-100)